import { Role } from '@property-copilot/shared';
import { PERMISSIONS, type Permission } from './permissions.js';

type RolePolicyMap = Record<Role, Permission[]>;

const adminPermissions: Permission[] = Object.values(PERMISSIONS);

export const rolePolicyMap: RolePolicyMap = {
  [Role.ADMIN]: adminPermissions,
  [Role.LANDLORD]: [
    PERMISSIONS.AUTH_ME_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PROPERTY_READ,
    PERMISSIONS.PROPERTY_WRITE,
    PERMISSIONS.PROPERTY_DELETE,
    PERMISSIONS.APPLICATION_READ,
    PERMISSIONS.APPLICATION_CREATE,
    PERMISSIONS.APPLICATION_REVIEW,
    PERMISSIONS.APPLICATION_DELETE,
  ],
  [Role.PM]: [
    PERMISSIONS.AUTH_ME_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PROPERTY_READ,
    PERMISSIONS.PROPERTY_WRITE,
    PERMISSIONS.APPLICATION_READ,
    PERMISSIONS.APPLICATION_CREATE,
    PERMISSIONS.APPLICATION_REVIEW,
  ],
  [Role.TENANT]: [
    PERMISSIONS.AUTH_ME_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.PROPERTY_READ,
    PERMISSIONS.APPLICATION_READ,
    PERMISSIONS.APPLICATION_CREATE,
  ],
};